import os 
import shutil
import logging
from dataclasses import dataclass

import pandas as pd 
import process



logger = logging.getLogger(__name__)

CHOPPER_QUAL = 10   # Quality cutoff for chopper
CHOPPER_LEN = 50    # Minimal length cutoff for chopper

@dataclass
class Preprocessing:
    idx_df : pd.DataFrame

    def __post_init__(self) -> None:
        self.make_dirs(self.idx_df.SampleID.values)
        self.run_filter()
        self.run_demultiplexing()
        self.move_samples(self.idx_df)
        self.cleanup()


    def make_dirs(self, sample_ids: list[str]) -> None:
        ''' Create a output directory for each sample '''
        os.makedirs("input/output", exist_ok=True)
        os.makedirs("input/misc", exist_ok=True)
        for sample in sample_ids:
            os.makedirs(f"input/output/{sample}", exist_ok=True)
        logger.info("Output directories successfully created")


    def run_filter(self) -> None:
        ''' 
        Filter ONT reads by quality and length.
        Default:
            Quality = 10 
            Lenght = 50
        '''
        logger.info("Start sequence filtering")
        unzip = process.run("gunzip -c input/input.fastq.gz")
        chopper = process.run(f"/root/miniconda3/envs/chopper/bin/chopper -q {CHOPPER_QUAL} -l {CHOPPER_LEN}", stdin=unzip.stdout)
        process.run("gzip > input/filtered.fastq.gz", stdin=chopper.stdout, chained=False)
        logger.info("Sequence filtering completed")


    def run_demultiplexing(self) -> None:
        '''Primer demultiplexing for sequenced reads'''
        logger.info("Start demultiplexing")
        process.run("python minibar.py -T -F input/IndexCombination.tsv input/filtered.fastq.gz -P ''", chained=False)
        logger.info("Finished demultiplexing")


    def move_samples(self, idx_df:pd.DataFrame) -> None:
        ''' Move samples to their corresponding output folder'''
        for sample in idx_df.SampleID.values:
            try:
                shutil.move(f"{sample}.fastq", f"input/output/{sample}/{sample}.fastq")
            except FileNotFoundError:
                pass 

        for file in os.listdir("input/"):
            if file.endswith(".fastq"):
                shutil.move(f"input/{file}", f"input/misc/{file}")


    def cleanup(self) -> None:
        ''' Delte unnecessary files generated by minibar'''
        for file in ["Multiple_Matches.fastq", "unk.fastq"]:
            if os.path.exists(file):
                os.remove(file)


if __name__ == "__main__":
    pass
